#
# Copyright © 2021, Ozone HIS <info@ozone-his.com>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

version: 1
build:
  # Unable to run tests because of no Docker agent available in OCD3 yet. https://mekomsolutions.atlassian.net/browse/INFRA-318
  bash_commands: "echo 'Build is handled by GitHub Actions. Skipping...' && exit 0"
deploy:
  bash_commands: "echo 'Publishing is handled by GitHub Actions. Skipping...' && exit 0"
